### ISSUE TITLE
Invalid credentials [IBM Cloud private]

### ISSUE THREAD

**Issue by manifestlifeinc** [IBM/ICp-banking-microservices#3]
Hello,

I'm currently unable to login and access the IBM Cloud Private catalog with an existing LinuxONE Community Cloud account referenced [in step 3](https://github.com/manifestlifeinc/ICp-banking-microservices#step-3---instantiate-the-banking-microservice-from-the-ibm-cloud-private-catalog-1).

The issue that I'm facing is that IBM Cloud Private will not accept my credentials associated with my LinuxONE community cloud account nor my IBMid.  Here is the [link](https://container.cloud.marist.edu:8443/oidc/login.jsp) I'm using to login IBM Cloud Private.

- When I click 'Try containers' [here](https://developer.ibm.com/linuxone/home-l1cc30-test/) it asks me to register for LinuxONE Community Cloud account which I'm unable to because I have an existing account. 

- When logged into the LinuxONE Community Cloud dashboard, I'm unable to click on the Containers tab on top.

Hopefully I can find some insight here regarding this issue. 

Thanks,
Manifest Life

**Comment by alexis-chretienne** [comment]
Hi Thank you for your support. I check with the LinuxOne CC administrators.
 
The ICP access is not available yet. My link was wrong. Please wait few weeks. 
 
Thank you.
 
 
 
                                                                        Best Regards,                         

                        Alexis CHRETIENNE                        IT Specialist CICS TS & API Enablement                        IBM Experienced Certified
                        MPLbank Team Leader - Book a demo now                        IBM Z                                                                                                
                                                                                                                                                        Mobile: +33 676758533                        E-mail: alexis.chretienne@fr.ibm.com                        Find me on:                                                                                                   Parc Technologique de la Pompignane                        Montpellier, Occitanie 34000                        France                        
 
 
----- Original message -----From: manifestlifeinc <notifications@github.com>To: IBM/ICp-banking-microservices <ICp-banking-microservices@noreply.github.com>Cc: Subscribed <subscribed@noreply.github.com>Subject: [IBM/ICp-banking-microservices] Invalid credentials [IBM Cloud private] (#3)Date: Fri, Aug 10, 2018 1:37 AM 
Hello,
I'm currently unable to login and access the IBM Cloud Private catalog with an existing LinuxONE Community Cloud account referenced in step 3.
The issue that I'm facing is that IBM Cloud Private will not accept my credentials associated with my LinuxONE community cloud account nor my IBMid. Here is the link I'm using to login IBM Cloud Private.
                When I click 'Try containers' here it asks me to register for LinuxONE Community Cloud account which I'm unable to because I have an existing account.                        When logged into the LinuxONE Community Cloud dashboard, I'm unable to click on the Containers tab on top.        
Hopefully I can find some insight here regarding this issue.
Thanks,Manifest Life
—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or mute the thread.

**Comment by manifestlifeinc** [comment]
Hi Alexis, thanks for your quick response. It is much appreciated.

Manifest Life
